/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import modelo.ImagenFondo;

/**
 *
 * @author Yohana Avila
 */
public class frmConsultar extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmConsultar
     */
    public frmConsultar() {
        setContentPane(new ImagenFondo(new ImageIcon(getClass().getResource("/img/car_minimalist.png")).getImage()));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnVehiculo = new javax.swing.ButtonGroup();
        btnVer_archivo = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Actualizar = new javax.swing.JButton();
        btnConectarDB = new javax.swing.JButton();
        txtTotalRecaudo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRecaudoAutos = new javax.swing.JTextField();
        txtRecaudoMotos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblDatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        RdbMoto = new javax.swing.JRadioButton();
        RdbAuto = new javax.swing.JRadioButton();
        lblimg = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        btnVer_archivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVer_archivo.setText("Ver Archivo");

        btn_Eliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Eliminar.setText("Eliminar");

        btn_Actualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Actualizar.setText("Actualizar");

        btnConectarDB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConectarDB.setText("Conectar BD");
        btnConectarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarDBActionPerformed(evt);
            }
        });

        txtTotalRecaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalRecaudoActionPerformed(evt);
            }
        });

        jLabel2.setText("Total Recaudado:");

        txtRecaudoAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecaudoAutosActionPerformed(evt);
            }
        });

        txtRecaudoMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecaudoMotosActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Recaudado Motos:");

        jLabel4.setText("Total Recaudado Autos:");

        TblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Formulario N°", "Propietario", "Tipo Vehiculo", "Placa", "Marca", "Modelo", "Valor", "IVA"
            }
        ));
        jScrollPane3.setViewportView(TblDatos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Lista de Registros");

        BtnVehiculo.add(RdbMoto);
        RdbMoto.setText("Moto");

        BtnVehiculo.add(RdbAuto);
        RdbAuto.setText("Auto");
        RdbAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbAutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnConectarDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(103, 103, 103)
                .addComponent(btnVer_archivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRecaudoMotos)
                            .addComponent(txtRecaudoAutos))
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalRecaudo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(347, 347, 347)
                        .addComponent(RdbMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RdbAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RdbMoto)
                            .addComponent(RdbAuto)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtTotalRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtRecaudoMotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRecaudoAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConectarDB)
                    .addComponent(btnVer_archivo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Actualizar)
                        .addComponent(btn_Eliminar)))
                .addGap(44, 44, 44))
        );

        RdbMoto.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RdbAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdbAutoActionPerformed

    private void txtRecaudoMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecaudoMotosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecaudoMotosActionPerformed

    private void txtRecaudoAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecaudoAutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecaudoAutosActionPerformed

    private void txtTotalRecaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalRecaudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalRecaudoActionPerformed

    private void btnConectarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConectarDBActionPerformed

    public JButton getBtn_Actualizar() {
        return btn_Actualizar;
    }

    public void setBtn_Actualizar(JButton btn_Actualizar) {
        this.btn_Actualizar = btn_Actualizar;
    }

    public JButton getBtn_Eliminar() {
        return btn_Eliminar;
    }

    public void setBtn_Eliminar(JButton btn_Eliminar) {
        this.btn_Eliminar = btn_Eliminar;
    }

    public JButton getBtnConectarDB() {
        return btnConectarDB;
    }

    public void setBtnConectarDB(JButton btnConectarDB) {
        this.btnConectarDB = btnConectarDB;
    }

    public JButton getBtnVer_archivo() {
        return btnVer_archivo;
    }

    public void setBtnVer_archivo(JButton btnVer_archivo) {
        this.btnVer_archivo = btnVer_archivo;
    }

    
    public JLabel getLblimg() {
        return lblimg;
    }

    public void setLblimg(JLabel lblimg) {
        this.lblimg = lblimg;
    }

    
    public ButtonGroup getBtnVehiculo() {
        return BtnVehiculo;
    }

    public void setBtnVehiculo(ButtonGroup BtnVehiculo) {
        this.BtnVehiculo = BtnVehiculo;
    }

    public JRadioButton getRdbAuto() {
        return RdbAuto;
    }

    public void setRdbAuto(JRadioButton RdbAuto) {
        this.RdbAuto = RdbAuto;
    }

    public JRadioButton getRdbMoto() {
        return RdbMoto;
    }

    public void setRdbMoto(JRadioButton RdbMoto) {
        this.RdbMoto = RdbMoto;
    }

    public JTable getTblDatos() {
        return TblDatos;
    }

    public void setTblDatos(JTable TblDatos) {
        this.TblDatos = TblDatos;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JTextField getTxtRecaudoAutos() {
        return txtRecaudoAutos;
    }

    public void setTxtRecaudoAutos(JTextField txtRecaudoAutos) {
        this.txtRecaudoAutos = txtRecaudoAutos;
    }

    public JTextField getTxtRecaudoMotos() {
        return txtRecaudoMotos;
    }

    public void setTxtRecaudoMotos(JTextField txtRecaudoMotos) {
        this.txtRecaudoMotos = txtRecaudoMotos;
    }

    public JTextField getTxtTotalRecaudo() {
        return txtTotalRecaudo;
    }

    public void setTxtTotalRecaudo(JTextField txtTotalRecaudo) {
        this.txtTotalRecaudo = txtTotalRecaudo;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnVehiculo;
    private javax.swing.JRadioButton RdbAuto;
    private javax.swing.JRadioButton RdbMoto;
    private javax.swing.JTable TblDatos;
    private javax.swing.JButton btnConectarDB;
    private javax.swing.JButton btnVer_archivo;
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblimg;
    private javax.swing.JTextField txtRecaudoAutos;
    private javax.swing.JTextField txtRecaudoMotos;
    private javax.swing.JTextField txtTotalRecaudo;
    // End of variables declaration//GEN-END:variables

}
