/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.JToolBar;

/**
 *
 * @author Yohana Avila
 */
public class frmPrincip extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincip
     */
    public frmPrincip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        ToolBar = new javax.swing.JToolBar();
        Btnbar_Registrar = new javax.swing.JButton();
        Btnbar_Consultar = new javax.swing.JButton();
        Btnbar_Salir = new javax.swing.JButton();
        ToolBar_fech = new javax.swing.JToolBar();
        Tgbtn_fecha = new javax.swing.JToggleButton();
        txtFecha = new javax.swing.JTextField();
        MenuBar = new javax.swing.JMenuBar();
        MnArchivo = new javax.swing.JMenu();
        opcRegistrar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        opcSalir = new javax.swing.JMenuItem();
        MnConsulta = new javax.swing.JMenu();
        opcConsultar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(153, 153, 153));
        escritorio.setPreferredSize(new java.awt.Dimension(665, 438));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        ToolBar.setRollover(true);

        Btnbar_Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registrar.png"))); // NOI18N
        Btnbar_Registrar.setText("Registrar");
        Btnbar_Registrar.setFocusable(false);
        Btnbar_Registrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btnbar_Registrar.setMaximumSize(new java.awt.Dimension(65, 60));
        Btnbar_Registrar.setMinimumSize(new java.awt.Dimension(65, 60));
        Btnbar_Registrar.setPreferredSize(new java.awt.Dimension(65, 60));
        Btnbar_Registrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Btnbar_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnbar_RegistrarActionPerformed(evt);
            }
        });
        ToolBar.add(Btnbar_Registrar);

        Btnbar_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultar.png"))); // NOI18N
        Btnbar_Consultar.setText("Consultar");
        Btnbar_Consultar.setFocusable(false);
        Btnbar_Consultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btnbar_Consultar.setPreferredSize(new java.awt.Dimension(65, 60));
        Btnbar_Consultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar.add(Btnbar_Consultar);

        Btnbar_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        Btnbar_Salir.setText("Salir");
        Btnbar_Salir.setFocusable(false);
        Btnbar_Salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btnbar_Salir.setMaximumSize(new java.awt.Dimension(65, 60));
        Btnbar_Salir.setMinimumSize(new java.awt.Dimension(65, 60));
        Btnbar_Salir.setPreferredSize(new java.awt.Dimension(65, 60));
        Btnbar_Salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar.add(Btnbar_Salir);

        ToolBar_fech.setRollover(true);

        Tgbtn_fecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fecha.png"))); // NOI18N
        Tgbtn_fecha.setSelected(true);
        Tgbtn_fecha.setText("Ver Fecha");
        Tgbtn_fecha.setFocusable(false);
        Tgbtn_fecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tgbtn_fecha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Tgbtn_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tgbtn_fechaActionPerformed(evt);
            }
        });
        ToolBar_fech.add(Tgbtn_fecha);

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        ToolBar_fech.add(txtFecha);

        MnArchivo.setText("Archivo");

        opcRegistrar.setText("Registrar");
        opcRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcRegistrarActionPerformed(evt);
            }
        });
        MnArchivo.add(opcRegistrar);
        MnArchivo.add(jSeparator1);

        opcSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcSalir.setText("Salir");
        MnArchivo.add(opcSalir);

        MenuBar.add(MnArchivo);

        MnConsulta.setText("Consulta");

        opcConsultar.setText("Consultar");
        opcConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcConsultarActionPerformed(evt);
            }
        });
        MnConsulta.add(opcConsultar);

        MenuBar.add(MnConsulta);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToolBar_fech, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(ToolBar_fech, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcRegistrarActionPerformed

    private void opcConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcConsultarActionPerformed

    private void Btnbar_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnbar_RegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btnbar_RegistrarActionPerformed

    private void Tgbtn_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tgbtn_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tgbtn_fechaActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    public JToggleButton getTgbtn_fecha() {
        return Tgbtn_fecha;
    }

    public void setTgbtn_fecha(JToggleButton Tgbtn_fecha) {
        this.Tgbtn_fecha = Tgbtn_fecha;
    }

    public JToolBar getToolBar_fech() {
        return ToolBar_fech;
    }

    public void setToolBar_fech(JToolBar ToolBar_fech) {
        this.ToolBar_fech = ToolBar_fech;
    }

    public JTextField getTxtFecha() {
        return txtFecha;
    }

    public void setTxtFecha(JTextField txtFecha) {
        this.txtFecha = txtFecha;
    }

    
    
    public void setMenuBar(JMenuBar MenuBar) {
        this.MenuBar = MenuBar;
    }

    public JMenu getMnArchivo() {
        return MnArchivo;
    }

    public void setMnArchivo(JMenu MnArchivo) {
        this.MnArchivo = MnArchivo;
    }

    public JMenu getMnConsulta() {
        return MnConsulta;
    }

    public void setMnConsulta(JMenu MnConsulta) {
        this.MnConsulta = MnConsulta;
    }

    public JButton getBtnbar_Consultar() {
        return Btnbar_Consultar;
    }

    public void setBtnbar_Consultar(JButton Btnbar_Consultar) {
        this.Btnbar_Consultar = Btnbar_Consultar;
    }

    public JButton getBtnbar_Registrar() {
        return Btnbar_Registrar;
    }

    public void setBtnbar_Registrar(JButton Btnbar_Registrar) {
        this.Btnbar_Registrar = Btnbar_Registrar;
    }

    public JButton getBtnbar_Salir() {
        return Btnbar_Salir;
    }

    public void setBtnbar_Salir(JButton Btnbar_Salir) {
        this.Btnbar_Salir = Btnbar_Salir;
    }

    public JToolBar getToolBar() {
        return ToolBar;
    }

    public void setToolBar(JToolBar ToolBar) {
        this.ToolBar = ToolBar;
    }
    
    
    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    public JPopupMenu.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JPopupMenu.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JMenuItem getOpcConsultar() {
        return opcConsultar;
    }

    public void setOpcConsultar(JMenuItem opcConsultar) {
        this.opcConsultar = opcConsultar;
    }

    public JMenuItem getOpcRegistrar() {
        return opcRegistrar;
    }

    public void setOpcRegistrar(JMenuItem opcRegistrar) {
        this.opcRegistrar = opcRegistrar;
    }

    public JMenuItem getOpcSalir() {
        return opcSalir;
    }

    public void setOpcSalir(JMenuItem opcSalir) {
        this.opcSalir = opcSalir;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnbar_Consultar;
    private javax.swing.JButton Btnbar_Registrar;
    private javax.swing.JButton Btnbar_Salir;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MnArchivo;
    private javax.swing.JMenu MnConsulta;
    private javax.swing.JToggleButton Tgbtn_fecha;
    private javax.swing.JToolBar ToolBar;
    private javax.swing.JToolBar ToolBar_fech;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem opcConsultar;
    private javax.swing.JMenuItem opcRegistrar;
    private javax.swing.JMenuItem opcSalir;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables

}
